"""Download the paper's consolidated Kaggle dataset and refresh local data.yaml paths."""

from __future__ import annotations

import argparse
import json
import os
import shutil
from pathlib import Path

from dotenv import load_dotenv

KAGGLE_DATASET = "gajendramandalcsvtu/custum-dataset-and-public-data-for-model-training"
DATASET_SLUG = "custum-dataset-and-public-data-for-model-training"

PROJECT_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_RAW_DIR = PROJECT_ROOT / "data" / "raw"
DEFAULT_DATA_YAML = PROJECT_ROOT / "configs" / "data.yaml"


def _ensure_kaggle_credentials() -> None:
    """Write ~/.kaggle/kaggle.json from env vars when present."""
    load_dotenv(PROJECT_ROOT / ".env")
    username = os.getenv("KAGGLE_USERNAME", "").strip()
    key = os.getenv("KAGGLE_KEY", "").strip() or os.getenv("KAGGLE_API_KEY", "").strip()

    kaggle_dir = Path.home() / ".kaggle"
    kaggle_json = kaggle_dir / "kaggle.json"
    if kaggle_json.exists():
        return

    if not username or not key:
        raise SystemExit(
            "Kaggle credentials not found. Place kaggle.json in ~/.kaggle/ "
            "or set KAGGLE_USERNAME and KAGGLE_KEY in .env (see .env.example)."
        )

    kaggle_dir.mkdir(parents=True, exist_ok=True)
    creds = {"username": username, "key": key}
    kaggle_json.write_text(json.dumps(creds), encoding="utf-8")
    try:
        os.chmod(kaggle_json, 0o600)
    except OSError:
        pass


def download_dataset(dest_dir: Path | None = None, force: bool = False) -> Path:
    """
    Download and extract the consolidated weapon/blunt-object dataset.

    Returns the path to the extracted dataset root (containing train/valid/test).
    """
    dest_dir = dest_dir or DEFAULT_RAW_DIR
    dest_dir.mkdir(parents=True, exist_ok=True)
    dataset_root = dest_dir / DATASET_SLUG

    if dataset_root.exists() and (dataset_root / "train" / "images").exists() and not force:
        print(f"Dataset already present at {dataset_root}")
        return dataset_root

    if force and dataset_root.exists():
        shutil.rmtree(dataset_root)

    _ensure_kaggle_credentials()

    # Prefer Kaggle CLI API for non-interactive downloads.
    try:
        from kaggle.api.kaggle_api_extended import KaggleApi

        api = KaggleApi()
        api.authenticate()
        print(f"Downloading {KAGGLE_DATASET} into {dest_dir} ...")
        api.dataset_download_files(KAGGLE_DATASET, path=str(dest_dir), unzip=True, quiet=False)
    except Exception as kaggle_err:
        print(f"Kaggle API download failed ({kaggle_err}); falling back to opendatasets...")
        import opendatasets as od

        # opendatasets downloads into cwd; change into dest_dir first.
        cwd = Path.cwd()
        try:
            os.chdir(dest_dir)
            od.download(f"https://www.kaggle.com/datasets/{KAGGLE_DATASET}")
        finally:
            os.chdir(cwd)

    if not dataset_root.exists():
        # Some extract layouts nest one extra folder — search for train/images.
        candidates = list(dest_dir.rglob("train/images"))
        if not candidates:
            raise FileNotFoundError(
                f"Download finished but could not find train/images under {dest_dir}"
            )
        dataset_root = candidates[0].parent.parent

    print(f"Dataset ready at {dataset_root}")
    return dataset_root


def write_data_yaml(dataset_root: Path, yaml_path: Path | None = None) -> Path:
    """Write/update configs/data.yaml with absolute path to the dataset."""
    yaml_path = yaml_path or DEFAULT_DATA_YAML
    yaml_path.parent.mkdir(parents=True, exist_ok=True)

    # Prefer path relative to configs/ when possible for portability.
    try:
        rel = os.path.relpath(dataset_root, yaml_path.parent).replace("\\", "/")
    except ValueError:
        rel = str(dataset_root).replace("\\", "/")

    content = f"""# Auto-generated by threat_detection.data.download — do not hand-edit paths blindly.
path: {rel}
train: train/images
val: valid/images
test: test/images

nc: 3
names:
  0: blunt_object
  1: gun
  2: knife
"""
    yaml_path.write_text(content, encoding="utf-8")
    print(f"Wrote {yaml_path}")
    return yaml_path


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Download Kaggle weapon detection dataset")
    parser.add_argument(
        "--dest",
        type=Path,
        default=DEFAULT_RAW_DIR,
        help="Directory to store the raw dataset",
    )
    parser.add_argument("--force", action="store_true", help="Re-download even if present")
    parser.add_argument(
        "--data-yaml",
        type=Path,
        default=DEFAULT_DATA_YAML,
        help="Path to write YOLO data.yaml",
    )
    args = parser.parse_args(argv)

    root = download_dataset(args.dest, force=args.force)
    write_data_yaml(root, args.data_yaml)


if __name__ == "__main__":
    main()
